In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.14.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
Z=np.zeros(10)

In [4]:
#内存大小
Z=np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


In [7]:
#说明文档
#np.info(np.add)

In [8]:
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
a=np.arange(10,50)

In [11]:
a1=a[::-1]
a1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [14]:
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
#非零位置索引
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [17]:
#单位矩阵
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.random((3,3,3))

array([[[0.57661019, 0.72804927, 0.47184026],
        [0.01227421, 0.37831984, 0.76306774],
        [0.97928117, 0.3018802 , 0.90823959]],

       [[0.33234956, 0.03223729, 0.37243677],
        [0.04847031, 0.85256334, 0.8117571 ],
        [0.29303936, 0.1422398 , 0.56367946]],

       [[0.70384819, 0.8032231 , 0.68729609],
        [0.71217926, 0.47778397, 0.00477695],
        [0.30250223, 0.56821693, 0.61272426]]])

In [27]:
a=np.random.random((10,10))
a_max,a_min=a.max(),a.min()
print(a_max,a_min)

0.9882732696182516 0.009160818406847904


In [28]:
a=np.random.randn(30)
a.mean()

-0.04301021910685596

In [29]:
# 创建一个二维数组，其中边界值为1，其余值为0
a=np.ones((7,7))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [31]:
# 对于一个存在在数组，如何添加一个用0填充的边界?
a1=np.pad(a,pad_width=1,mode="constant",constant_values=0)
a1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
0 * np.nan

nan

In [33]:
np.nan == np.nan

False

In [34]:
np.inf > np.nan

False

In [35]:
np.nan - np.nan

nan

In [38]:
0.3 == 3 * 0.1

False