In [1]:
import pandas as pd
import numpy as np
from pandas import  Series,DataFrame

# pandas的数据结构:Series、DataFrame

In [2]:
obj=Series([4,7,-5,3])

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2=Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']=9
obj2

d    4
b    7
a    9
c    3
dtype: int64

In [14]:
obj2[obj2>5]

b    7
a    9
dtype: int64

In [17]:
np.sqrt(obj2)

d    2.000000
b    2.645751
a    3.000000
c    1.732051
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
9 in obj2

False

In [21]:
#字典创建Series
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
sdates=['ca','Ohio','Oregon','Texas']
obj4=Series(sdata,index=sdates)
obj4

ca            NaN
Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

In [24]:
#检测缺失值 
pd.isnull(obj4)

ca         True
Ohio      False
Oregon    False
Texas     False
dtype: bool

In [25]:
# name属性
obj4.name='difang'
obj4.index.name='state'
obj4

state
ca            NaN
Ohio      35000.0
Oregon    16000.0
Texas     71000.0
Name: difang, dtype: float64

In [27]:
# DataFrame为表格型数据结构，含有有序的列，由Series组成的字典
data={'state':['oh','oh','oh','ne','ne'],
     'year':[20,20,201,21,34],
     'pop':[1.7,10,9.8,2.1,5.2]}
frame=DataFrame(data)
frame

state  year   pop
0    oh    20   1.7
1    oh    20  10.0
2    oh   201   9.8
3    ne    21   2.1
4    ne    34   5.2

In [28]:
DataFrame(data,columns=['year','state','pop'])

year state   pop
0    20    oh   1.7
1    20    oh  10.0
2   201    oh   9.8
3    21    ne   2.1
4    34    ne   5.2

In [29]:
frame2=DataFrame(data,columns=['year','state','pop','jz'],
                index=['one','two','three','four','five'])
frame2

year state   pop   jz
one      20    oh   1.7  NaN
two      20    oh  10.0  NaN
three   201    oh   9.8  NaN
four     21    ne   2.1  NaN
five     34    ne   5.2  NaN

In [30]:
frame2.columns

Index(['year', 'state', 'pop', 'jz'], dtype='object')

In [34]:
frame2.year

one       20
two       20
three    201
four      21
five      34
Name: year, dtype: int64

In [35]:
frame2.ix['three']
# ix可以看某一行

c:\users\jazlyn\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     201
state     oh
pop      9.8
jz       NaN
Name: three, dtype: object

In [42]:
frame2.jz=np.arange(5)
frame2

year state   pop  jz
one      20    oh   1.7   0
two      20    oh  10.0   1
three   201    oh   9.8   2
four     21    ne   2.1   3
five     34    ne   5.2   4

In [43]:
val=Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2.jz=val
frame2

year state   pop   jz
one      20    oh   1.7  NaN
two      20    oh  10.0 -1.2
three   201    oh   9.8  NaN
four     21    ne   2.1 -1.5
five     34    ne   5.2 -1.7

In [44]:
frame2.values

array([[20, 'oh', 1.7, nan],
       [20, 'oh', 10.0, -1.2],
       [201, 'oh', 9.8, nan],
       [21, 'ne', 2.1, -1.5],
       [34, 'ne', 5.2, -1.7]], dtype=object)

索引对象

In [46]:
obj=Series(range(9),index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [47]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [49]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

In [51]:
# index对象不可修改
obj.index[1]='f'

TypeError: Index does not support mutable operations

In [52]:
# Index可以实现轴索引
index=pd.Index(np.arange(3))
index

Int64Index([0, 1, 2], dtype='int64')

In [54]:
obj2=Series([1.5,-2.5,0],index=index)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [55]:
obj2.index is index

True

In [3]:
obj=Series([4.5,7.2,-5.3,3.6],index=['a','b','c','d'])
obj

a    4.5
b    7.2
c   -5.3
d    3.6
dtype: float64

In [4]:
# 新索引与引入缺失值
obj2=obj.reindex(['a','b','c','d','g'],fill_value=1)
obj2

a    4.5
b    7.2
c   -5.3
d    3.6
g    1.0
dtype: float64

In [8]:
frame=DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],
               columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [9]:
frame2=frame.reindex(['a','b','c','d'],method='bfill')
frame2

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     3      4           5
d     6      7           8

Pandas基本功能

In [7]:
# 删除任意轴索引值
new_obj=obj.drop('c')
new_obj

a    4.5
b    7.2
d    3.6
dtype: float64

In [12]:
# 删除任意轴索引值
frame2.drop(['c'])

Ohio  Texas  California
a     0      1           2
b     3      4           5
d     6      7           8

In [16]:
# 索引、选取、过滤
#Series索引
obj=Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [18]:
print(obj['b'])
print(obj[1])
print(obj[2:4])
print(obj[['a','b']])
print(obj[obj>1])
print(obj[[1,3]])

1.0
1.0
c    2.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64
c    2.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64


In [19]:
frame=DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],
               columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [35]:
print(frame['Ohio'])
print("...............................")
print(frame[:2])
print("...............................")
print(frame.ix['a',['Ohio','Texas']])
print("...............................")
print(frame.ix[[0,1],[0,2]])
print("...............................")
# 前面是取行，后面取列：行列顺序，但也可以做判断
print(frame.ix[frame.California>2,])

a    0
c    3
d    6
Name: Ohio, dtype: int32
...............................
   Ohio  Texas  California
a     0      1           2
c     3      4           5
...............................
Ohio     0
Texas    1
Name: a, dtype: int32
...............................
   Ohio  California
a     0           2
c     3           5
...............................
   Ohio  Texas  California
c     3      4           5
d     6      7           8


c:\users\jazlyn\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """
c:\users\jazlyn\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  import sys
c:\users\jazlyn\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __na

DataFrame与Series之间的运算

In [36]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [37]:
arr[0]

array([0., 1., 2., 3.])

In [38]:
# 广播
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [40]:
frame=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                index=list('abcd'))
frame

b     d     e
a  0.0   1.0   2.0
b  3.0   4.0   5.0
c  6.0   7.0   8.0
d  9.0  10.0  11.0

In [42]:
ser=frame.ix[0]
ser

c:\users\jazlyn\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


b    0.0
d    1.0
e    2.0
Name: a, dtype: float64

In [43]:
frame-ser

b    d    e
a  0.0  0.0  0.0
b  3.0  3.0  3.0
c  6.0  6.0  6.0
d  9.0  9.0  9.0

函数应用和映射

In [44]:
f=lambda x:x.max()-x.min()
frame.apply(f)

b    9.0
d    9.0
e    9.0
dtype: float64

In [45]:
# axis=0代表按列计算，axis=1代表按行计算
print(frame.apply(f,axis=0))
print(frame.apply(f,axis=1))

b    9.0
d    9.0
e    9.0
dtype: float64
a    2.0
b    2.0
c    2.0
d    2.0
dtype: float64


排序

In [52]:
# DataFrame用sort_index
print(frame.sort_index(by='b'))
print("...............................")
print(frame.sort_values('e',ascending=False))

     b     d     e
a  0.0   1.0   2.0
b  3.0   4.0   5.0
c  6.0   7.0   8.0
d  9.0  10.0  11.0
...............................
     b     d     e
d  9.0  10.0  11.0
c  6.0   7.0   8.0
b  3.0   4.0   5.0
a  0.0   1.0   2.0


c:\users\jazlyn\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  


In [54]:
# Series用order
obj=Series(np.arange(4.),index=['a','b','c','d'])
# obj.sort_index(ascending=False)
obj.rank()

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64